[修复] list-lite组件的图标与文本未垂直居中
rdkmaster/jigsaw pull request #1315
Opened 2021-02-05 07:13 UTC by Gloryoftan

Change-Id: Id3cc0f1886d537dba69ad2e4e2326150b58e4ff3

2021-02-07 05:09 UTC, hpyou commented
@Gloryoftan  优化或者修复的内容，要截图说明一下哪里有问题或者哪里需要优化

2021-02-07 06:29 UTC, Gloryoftan commented
图标与文本垂直居中。

![image](https://user-images.githubusercontent.com/41236821/107138700-d7937f00-6950-11eb-9676-0b52db7c3be4.png)

2021-02-07 07:19 UTC, hpyou commented
> 图标与文本垂直居中。
> 
> ![image](https://user-images.githubusercontent.com/41236821/107138700-d7937f00-6950-11eb-9676-0b52db7c3be4.png)

修改前和修改后的区别截图看下

2021-02-07 08:28 UTC, Gloryoftan commented
> > 图标与文本垂直居中。
> > ![image](https://user-images.githubusercontent.com/41236821/107138700-d7937f00-6950-11eb-9676-0b52db7c3be4.png)
> 
> 修改前和修改后的区别截图看下

原issue地址：https://gitlab.zte.com.cn/10045812/ng-eval/issues/2398

2021-02-07 08:50 UTC, hpyou approved these changes

2021-02-07 09:05 UTC, hpyou commented on src/jigsaw/pc-components/list-and-tile/list-lite.ts
>                      <span j-sub-title *ngIf="item?.suffixIcon" class="{{item?.suffixIcon}}" style="font-size:12px; margin-top:3px"></span>
sub-title没有做溢出处理把？

2021-02-07 09:08 UTC, hpyou requested changes
sub-title没有做溢出处理把？

2021-02-07 09:11 UTC, rdkmaster commented
http://localhost:4200/#/pc/list-lite/with-icon 有问题

![image](https://user-images.githubusercontent.com/16191626/107141957-dff6b480-6966-11eb-8adb-2e256ed4a846.png)

2021-02-08 10:47 UTC, Gloryoftan commented
> http://localhost:4200/#/pc/list-lite/with-icon 有问题，正常情况下，第二个图标应该是在同一行上
> 
> ![image](https://user-images.githubusercontent.com/16191626/107141957-dff6b480-6966-11eb-8adb-2e256ed4a846.png)

![image](https://user-images.githubusercontent.com/41236821/107209705-223ef500-6a3e-11eb-95c4-fe7d0e35f056.png)

2021-02-08 11:12 UTC, rdkmaster approved these changes

2021-02-08 11:13 UTC, merged