[新增] 新增点击已选日期清空日期功能，解决了@7260
rdkmaster/jigsaw pull request #1448
Opened 2021-06-09 02:30 UTC by Gloryoftan

Change-Id: Ieac2df206cc6eced7b512e449d300530d06257d8

2021-06-09 06:43 UTC, rdkmaster commented on src/jigsaw/pc-components/date-and-time/date-picker.ts
> +    public clearDate() {
注意内部的公共方法命名规则

2021-06-10 06:02 UTC, 10229428 commented
貌似只改了date-picker，data-time-picker没有改

![1](https://user-images.githubusercontent.com/42016535/121472862-60502380-c9f4-11eb-9862-cfcfcca6c218.gif)
![2](https://user-images.githubusercontent.com/42016535/121472872-634b1400-c9f4-11eb-9135-e438605538f3.gif)

2021-06-16 01:56 UTC, 10229428 reviewed
月粒度无法清除

![image](https://user-images.githubusercontent.com/42016535/122146156-1bf7d400-ce89-11eb-84af-78a6cb1e4a35.png)

2021-06-16 02:04 UTC, 10229428 commented
date-time-select中，清除了日期里面选择的值，但是在设置combo值的时候，空值被过滤了：

![image](https://user-images.githubusercontent.com/42016535/122146629-033bee00-ce8a-11eb-9df5-a7c1774de42b.png)

![image](https://user-images.githubusercontent.com/42016535/122146750-2b2b5180-ce8a-11eb-93f0-04c0162473b5.png)

2021-06-16 02:07 UTC, 10229428 commented
截图中的demo，清除之后，combo中显示异常：

![image](https://user-images.githubusercontent.com/42016535/122147007-a8ef5d00-ce8a-11eb-8292-2af4016ff960.png)

2021-06-18 02:53 UTC, hpyou commented
需要合并master，与确认按钮一起测一下

2021-06-18 02:56 UTC, hpyou commented
和确认按钮使用时，limit没有自动跳到合法的时间
![GIF](https://user-images.githubusercontent.com/15992591/122499592-bf7cec00-d023-11eb-8cc3-836e544a2a36.gif)

2021-06-18 05:16 UTC, hpyou commented
这个应该是确认按钮的问题，和本PR无关，可以等确认按钮改完了，再合并测一下

2021-06-22 07:29 UTC, rdkmaster commented
现在的问题是，比如粒度是天，我点开月份的时候，选择了同一个月的时候，依然算作取消选择了

2021-06-22 07:41 UTC, rdkmaster commented
> 现在的问题是，比如粒度是天，我点开月份的时候，选择了同一个月的时候，依然算作取消选择了

支持复选取消的入口，我感觉应该是：
1. 如果粒度为天/时/分/秒，应该仅为日期
2. 如果粒度为月时，应该复选月份取消
3. 粒度为年，不考虑

2021-06-22 09:09 UTC, rdkmaster approved these changes

2021-06-22 09:10 UTC, rdkmaster commented
时间段选择器没有实现取消功能

![Uploading aa.gif…]()

2021-06-23 02:11 UTC, rdkmaster requested changes
按照留言修改range时间选择器的问题。取消一个时，则取消整个时间段的值。这个好改就改，如果不好改，请留言说明，先不修改。这个时间段选择器是要重构的，现在花很多力气修改没有意义。

2021-06-28 06:08 UTC, Gloryoftan commented
> 按照留言修改range时间选择器的问题。取消一个时，则取消整个时间段的值。这个好改就改，如果不好改，请留言说明，先不修改。这个时间段选择器是要重构的，现在花很多力气修改没有意义。

不好弄，可以先重构

2021-06-28 06:47 UTC, rdkmaster approved these changes

2021-06-28 06:47 UTC, merged