[故障] 修复穿梭框副标题换行的问题，解决了@7171
rdkmaster/jigsaw pull request #1525
Opened 2021-07-05 02:53 UTC by hpyou

Change-Id: Ifeb7214d82ae2feff473cc0bb58241c0a4dddeea

2021-07-05 03:14 UTC, rdkmaster approved these changes

2021-07-05 03:16 UTC, rdkmaster commented
![image](https://user-images.githubusercontent.com/16191626/124413052-71d1e480-dd82-11eb-872d-c634f1cf0caa.png)

2021-07-05 03:17 UTC, rdkmaster commented
![image](https://user-images.githubusercontent.com/16191626/124413122-9c23a200-dd82-11eb-9061-c71d5bb240bc.png)

2021-07-05 03:43 UTC, rdkmaster requested changes
按照留言修改

2021-07-05 07:10 UTC, hpyou commented
改成这样了

![image](https://user-images.githubusercontent.com/15992591/124431552-12d09780-dda3-11eb-9099-7e8caaf7f685.png)

![image](https://user-images.githubusercontent.com/15992591/124431604-21b74a00-dda3-11eb-9d4f-c905b9d00005.png)

2021-07-05 09:03 UTC, rdkmaster commented
![image](https://user-images.githubusercontent.com/16191626/124446361-ede42080-ddb2-11eb-8ee2-4d23bcb824ee.png)

2021-07-05 09:08 UTC, hpyou commented
![image](https://user-images.githubusercontent.com/15992591/124447105-a27e4200-ddb3-11eb-9a69-1e9c33fa7961.png)

2021-07-05 09:35 UTC, hpyou commented
![image](https://user-images.githubusercontent.com/15992591/124450823-61882c80-ddb7-11eb-9af9-69c4edeceacb.png)

2021-07-05 11:23 UTC, rdkmaster commented on src/jigsaw/pc-components/transfer/transfer.scss
> +                min-width: 66%;
副标题是否要相应改为34%？

2021-07-06 01:43 UTC, hpyou commented
在副标题上加min-width，当没有副标题时，会出现：
![image](https://user-images.githubusercontent.com/15992591/124530166-92f80b00-de3e-11eb-96e2-8210e68f0f99.png)

2021-07-06 02:57 UTC, rdkmaster commented on src/jigsaw/pc-components/transfer/transfer.scss
> +                min-width: 66%;
经过测试，我把比例恢复到50%了。

2021-07-06 02:57 UTC, rdkmaster approved these changes

2021-07-06 02:57 UTC, merged